name: Purge Cache

on:
  workflow_dispatch:

permissions: 
  actions: write

jobs:
  purge-cache:
    name: Purge Cache
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      # https://github.com/MyAlbum/purge-cache
      - name: Purge Build Cache
        uses: MyAlbum/purge-cache@v2
        with:
          accessed: true # Purge caches by their last accessed time (default: true)
          created: true # Purge caches by their created time (default: false)
          debug: true # turn on debug logging (default: false)
          max-age: 86400 # Leave only caches accessed/created in the last 1 day (default: 604800 - 7 days)